name: Deploy Serverless Functions to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install DigitalOcean CLI (doctl)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install Serverless Plugin
        run: |
          doctl serverless install
      - name: Deploy to Namespace lionfish-fn-namespace
        run: |
          doctl serverless connect lionfish-fn-namespace
          doctl serverless deploy . --remote-build
